### ISSUE TITLE
wallets[i].connect is not a function

### ISSUE THREAD

**Issue by sunShineLoveMe** [WTFAcademy/WTFEthers#17]
你好，在https://github.com/WTFAcademy/WTFEthers/blob/main/16_MultiCollect/readme.md
这个教程中，在批量归集钱包的ETH代币这部分代码

`console.log("\n4. 批量归集20个钱包的ETH")
const txSendETH = {
    to: wallet.address,
    value: amount
}
for (let i = 0; i < numWallet; i++) {
    // 将钱包连接到provider
    let walletiWithProvider = **wallets[i].connect(provider)**
    var tx = await walletiWithProvider.sendTransaction(txSendETH)
    console.log(`第 ${i+1} 个钱包 ${walletiWithProvider.address} ETH 归集开始`)
}
await tx.wait()
console.log(`ETH 归集结束`)`

运行之后，出现报错：
报错信息是：
`UnhandledPromiseRejectionWarning: TypeError: wallets[i].connect is not a function`

请教一下如何解决？感谢！

**Comment by AmazingAng** [comment]
要运行js完整代码，可以在这一讲的文件夹中找到。
