### ISSUE TITLE
17_MerkleTree 文章中参数填写有误

### ISSUE THREAD

**Issue by sunShineLoveMe** [WTFAcademy/WTFEthers#18]
你好，在https://github.com/WTFAcademy/WTFEthers/blob/main/17_MerkleTree/readme.md 这个文中有一处地方表述有误，

![image](https://user-images.githubusercontent.com/19338577/191520727-8a3efd24-9955-4e84-a551-a3d2bc5515cd.png)

红色框中的变量

**Comment by AmazingAng** [comment]
谢谢 已改正
